language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
      env: PHPCS=true
    - php: hhvm


before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit
  - if [[ "$PHPCS" == "true" ]]; then vendor/bin/phpcs src --standard=build/phpcs/ruleset.xml -np; fi

notifications:
    on_success: never
    on_failure: always